name: Deploy Frontend (develop → /homolog)

on:
  push:
    branches:
      - develop 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Node.js para o Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Instalar dependências do Frontend
        run: |
          cd frontend  # Ir para a pasta do frontend
          npm ci  # Usar npm ci para garantir que as dependências do frontend sejam instaladas

      - name: Build do Frontend
        run: |
          cd frontend  # Novamente, garantir que estamos no diretório correto
          npm run build  # Executar o build no frontend

      - name: Mover build para pasta /homolog
        run: |
          mkdir -p out/homolog
          mv frontend/dist/* out/homolog/  # Mover o build gerado (agora é a pasta 'dist') para o diretório correto

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          destination_dir: .
          publish_branch: gh-pages
